version: '3.8' # Specifies the version of the Docker Compose file format.

services: # This is where we define all the individual services (containers).

  # --- Service 1: The Database ---
  postgres_db:
    image: postgres:13 # Uses a pre-built PostgreSQL 13 image from Docker Hub.
    container_name: hospital_postgres # A friendly name for this container.
    environment: # Sets environment variables inside the container.
      POSTGRES_USER: user # The username for the database.
      POSTGRES_PASSWORD: password # The password for the database.
      POSTGRES_DB: hospital_data # Creates a database with this name upon startup.
    volumes:
      # Creates a persistent storage volume for the database data.
      # This ensures data is not lost when the container is stopped or removed.
      - postgres_volume:/var/lib/postgresql/data
    ports:
      # Maps port 5432 on your local machine to port 5432 inside the container,
      # allowing you to connect to the database from your computer if needed.
      - "5432:5432"

  # --- Service 2: The ETL Application ---
  etl_service:
    build: ./etl_app # Tells Docker Compose to build an image from the Dockerfile in the `etl_app` directory.
    container_name: hospital_etl # A friendly name for this container.
    depends_on:
      - postgres_db # This is crucial: it ensures that `postgres_db` is started and ready before this service starts.
    environment: # Environment variables passed to the ETL script.
      DB_USER: user
      DB_PASSWORD: password
      DB_HOST: postgres_db # The hostname to connect to the database. Docker networking makes services available by their service name.
      DB_NAME: hospital_data
    volumes:
      # Mounts the local `./data` directory into the `/app/data` directory inside the container.
      # This is how the ETL script gets access to the CSV files.
      - ./data:/app/data

  # --- Service 3: The Dashboard Application ---
  dashboard_service:
    build: ./dashboard_app # Builds an image from the Dockerfile in the `dashboard_app` directory.
    container_name: hospital_dashboard # A friendly name for this container.
    depends_on:
      - postgres_db # Ensures the database is running before the dashboard starts.
    ports:
      - "8501:8501" # Maps port 8501 on your machine to port 8501 in the container, so you can access the Streamlit app.
    environment: # Environment variables for the dashboard to connect to the database.
      DB_USER: user
      DB_PASSWORD: password
      DB_HOST: postgres_db
      DB_NAME: hospital_data

volumes:
  postgres_volume: # Defines the named volume used by the `postgres_db` service.